<?php

namespace Umbria\OpenApiBundle\Controller\Tourism;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BaseController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Umbria\OpenApiBundle\Controller\Tourism\BaseController();
        return $instance;
    }
}
