<?php

namespace Umbria\OpenApiBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class EntitiesUpdateController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Umbria\OpenApiBundle\Controller\EntitiesUpdateController($container->get('doctrine.orm.entity_manager', 1));
        return $instance;
    }
}
