<?php

namespace Umbria\ProLocoBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SUAPEController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Umbria\ProLocoBundle\Controller\SUAPEController();
        return $instance;
    }
}
