parameters:

    url_proposal: http://odn.cloudapp.net/dataset/33be3077-9612-4ef2-bf39-c0eb01dd6079/resource/258536a5-39e0-46bf-81c9-b118fd70aaed/download/proposteitIT.zipproposteitIT.rdf
    url_proposal_silk: null
    proposal_days_to_old: 0

    url_attractor: http://dati.umbria.it/dataset/ab39e23d-540f-4aa1-b27f-3fb244837545/resource/59822c9d-c9d6-4bcd-87c6-cd35a9f3d41d/download/attrattoriitit.zipattrattoriitit.rdf
    url_attractor_silk: http://dati.umbria.it/dataset/ab39e23d-540f-4aa1-b27f-3fb244837545/resource/2d9c13bf-d48c-4df2-b272-8f183c06c4c0/download/sameasdbpediaresource.rdf
    url_attractor_silk_located_in: http://dati.umbria.it/dataset/ab39e23d-540f-4aa1-b27f-3fb244837545/resource/138b1d6c-3f01-407d-9b5d-36841442d44b/download/locatedindbpediaresource.rdf
    attractor_days_to_old: 0

    url_event: http://dati.umbria.it/dataset/410faa97-546b-4362-a6d7-f8794d18ed19/resource/795338cb-d5b6-40c2-98ad-05fcad7f194c/download/eventiitit.zipeventiitit.rdf
    url_event_silk: null
    event_days_to_old: 0

    url_travel_agency: http://odn.cloudapp.net/dataset/a87cee68-4682-4915-9309-d432f2546434/resource/7f7df02d-0ec3-4aa9-b41e-fb2729b9af46/download/agenzie-turisticheitIT.zipagenzie-turisticheitIT.rdf
    url_travel_agency_silk: null
    travel_agency_days_to_old: 0

    url_consortium: http://odn.cloudapp.net/dataset/617e0893-9eea-4778-81cb-a18602928a6c/resource/f390fc3f-e648-404b-99ef-27ff1afc7881/download/consorziitIT.zipconsorziitIT.rdf
    url_consortium_silk: null
    consortium_days_to_old: 0

    url_profession: http://odn.cloudapp.net/dataset/f8d3ec7a-68a7-400f-9dfe-39b95984c2aa/resource/5ff6581c-6fd6-4f8b-acc0-40458f015956/download/professioni-turisticheitIT.zipprofessioni-turisticheitIT.rdf
    url_profession_silk: null
    profession_days_to_old: 0

    url_iat: http://odn.cloudapp.net/dataset/d2cc6cd2-0eac-4497-9dab-ce11a998bf9a/resource/feebf21b-74c4-4158-a3cc-33362f85708b/download/iatitIT.zipiatitIT.rdf
    url_iat_silk: null
    iat_days_to_old: 0

services:
    umbria_open_api.curl_builder:
        class: Umbria\OpenApiBundle\Service\CurlBuilder
        arguments: [@doctrine.orm.entity_manager, @jms_serializer]
    umbria_open_api.filter_bag:
        class: Umbria\OpenApiBundle\Service\FilterBag