version: "2"
services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'db_prova_openapi'
      #MYSQL_ALLOW_EMPTY_PASSWORD: 1
      #MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    volumes:
      - ./.database:/var/lib/mysql
  web:
    build: ./
    depends_on:
      - mysql
    container_name: web
    links:
      - mysql:mysql
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/

# aggiunte manualmente 
    x-environment:
        &default-environment
            XDEBUG_ENABLE: "true"
            DOCKERHOST: host.docker.internal