umbria_open_api:
    resource: "@UmbriaOpenApiBundle/Resources/config/routing.yml"
    prefix:   /

nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /open-api/doc

shaygan_telegram_bot_api:
    resource: "@ShayganTelegramBotApiBundle/Resources/config/routing.yml"