umbria_open_api:
    resource: "@UmbriaOpenApiBundle/Resources/config/routing.yml"
    prefix:   /

umbria_pro_loco:
    resource: "@UmbriaProLocoBundle/Resources/config/routing.yml"
    prefix:   /open-api/example

nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /open-api/doc
