<?php

namespace Umbria\OpenApiBundle\Repository\Tourism\GraphsEntities;

use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityRepository;

/**
 * AttractorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttractorRepository extends EntityRepository
{
    /**
     * @param $date \DateTime
     * @return \Doctrine\Common\Collections\Collection
     */
    public function findByLastUpdateAtBefore($date)
    {
        $criteria = new Criteria();
        $criteria->where($criteria->expr()->lt('lastUpdateAt', $date));
        return $this->matching($criteria);
    }
}
