<?php

namespace Umbria\OpenApiBundle\Repository\Tourism\GraphsEntities;

/**
 * IatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IatRepository extends \Doctrine\ORM\EntityRepository
{
}
