<?php

namespace Umbria\OpenApiBundle\Repository\Tourism\GraphsEntities;

/**
 * ProfessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessionRepository extends \Doctrine\ORM\EntityRepository
{
}
