umbria_pro_loco_attractor:
    resource: "@UmbriaProLocoBundle/Resources/config/routing/attractor.yml"
    prefix:   /tourism/attractor

umbria_pro_loco_proposal:
    resource: "@UmbriaProLocoBundle/Resources/config/routing/proposal.yml"
    prefix:   /tourism/proposal

umbria_pro_loco_event:
    resource: "@UmbriaProLocoBundle/Resources/config/routing/event.yml"
    prefix:   /tourism/event

umbria_pro_loco_travelagency:
    resource: "@UmbriaProLocoBundle/Resources/config/routing/travelagency.yml"
    prefix:   /travel-agency

umbria_pro_loco_consortium:
    resource: "@UmbriaProLocoBundle/Resources/config/routing/consortium.yml"
    prefix:   /consortium

umbria_pro_loco_profession:
    resource: "@UmbriaProLocoBundle/Resources/config/routing/profession.yml"
    prefix:   /profession

umbria_pro_loco_iat:
    resource: "@UmbriaProLocoBundle/Resources/config/routing/iat.yml"
    prefix:   /iat

umbria_pro_loco_sport_facility:
    resource: "@UmbriaProLocoBundle/Resources/config/routing/sport_facility.yml"
    prefix:   /sport_facility

umbria_pro_loco_accomodation:
    resource: "@UmbriaProLocoBundle/Resources/config/routing/accomodation.yml"
    prefix:   /tourism/accomodation

umbria_pro_loco_homepage:
    path:     /tourism/map
    defaults: { _controller: UmbriaProLocoBundle:Default:index }

umbria_pro_loco_statistiche:
    path:     /statistiche
    defaults: { _controller: UmbriaProLocoBundle:SUAPE:index }

umbria_pro_loco_suape:
    path:     /statistiche/SUAPE
    defaults: { _controller: UmbriaProLocoBundle:SUAPE:index }

umbria_pro_loco_istanze:
    path:     /statistiche/istanze
    defaults: { _controller: UmbriaProLocoBundle:Istanze:index }

umbria_pro_loco_suape_execute_sparql_query:
    path:     /statistiche/SUAPE/execute_sparql_query/
    defaults: {_controller: UmbriaProLocoBundle:SUAPE:executeSparqlQuery }
    methods:  [POST]


umbria_pro_loco_istanze_execute_sparql_query:
    path:     /statistiche/istanze/execute_sparql_query/
    defaults: {_controller: UmbriaProLocoBundle:Istanze:executeSparqlQuery }
    methods:  [POST, GET]