<?php

namespace Umbria\OpenApiBundle\Repository;

/**
 * ExternalResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExternalResourceRepository extends \Doctrine\ORM\EntityRepository
{
}
