<?php

namespace Umbria\OpenApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TourismRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourismRepository extends EntityRepository
{
}
