<?php

namespace Umbria\OpenApiBundle\Repository\Tourism;

use Doctrine\ORM\EntityRepository;

/**
 * AttractorRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttractorRepository extends EntityRepository
{
    public function getAllQuery()
    {
        $qb = $this->createQueryBuilder('a');

        return $qb->getQuery();
    }
}
