<?php

namespace Umbria\OpenApiBundle\Repository\Tourism;

use Doctrine\ORM\EntityRepository;

/**
 * CoordinateRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordinateRepository extends EntityRepository
{
}
