<?php

namespace Umbria\OpenApiBundle\Repository\Tourism;

/**
 * PhoneRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneRepository extends \Doctrine\ORM\EntityRepository
{
}
