<?php

namespace Umbria\OpenApiBundle\Repository\Tourism;

/**
 * ProfessionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllQuery()
    {
        $qb = $this->createQueryBuilder('p');

        return $qb->getQuery();
    }
}
