<?php

namespace Umbria\OpenApiBundle\Repository\Tourism;

use Doctrine\ORM\EntityRepository;

/**
 * ProposalRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProposalRepository extends EntityRepository
{
    public function getAllQuery()
    {
        $qb = $this->createQueryBuilder('p');

        return $qb->getQuery();
    }
}
