<?php

namespace Umbria\OpenApiBundle\Repository\Tourism;

/**
 * TravelAgencyRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravelAgencyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllQuery()
    {
        $qb = $this->createQueryBuilder('ta');

        return $qb->getQuery();
    }
}
