attractor_index:
    path:     /
    defaults: { _controller: "UmbriaProLocoBundle:Attractor:index" }
    methods:  GET

attractor_show:
    path:     /{id}/show
    defaults: { _controller: "UmbriaProLocoBundle:Attractor:show" }
    methods:  GET