iat_index:
    path:     /
    defaults: { _controller: "UmbriaProLocoBundle:Iat:index" }
    methods:  GET

iat_show:
    path:     /{id}/show
    defaults: { _controller: "UmbriaProLocoBundle:Iat:show" }
    methods:  GET