proposal_index:
    path:     /
    defaults: { _controller: "UmbriaProLocoBundle:Proposal:index" }
    methods:  [GET,POST]

proposal_show:
    path:     /{id}/show
    defaults: { _controller: "UmbriaProLocoBundle:Proposal:show" }
    methods:  GET
