travelagency_index:
    path:     /
    defaults: { _controller: "UmbriaProLocoBundle:TravelAgency:index" }
    methods:  GET

travelagency_show:
    path:     /{id}/show
    defaults: { _controller: "UmbriaProLocoBundle:TravelAgency:show" }
    methods:  GET
